services:
  mysql:
    image: mysql:8.4          # MySQL 8.1 image
    container_name: mysql-test-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123   # Set your root password here
      MYSQL_DATABASE: test                # Optional: initial database
    ports:
      - "3306:3306"                       # Maps host 3306 to container 3306
#    volumes:
#      - ./data:/var/lib/mysql         # Persistent data storage
